# ROOT APPLICATION HAS NO AUTO SYNC. MUST APPLY IT MANUALLY  ON EVERY SINGLE CHANGE!

# Todo change to Application set https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # todo make repoURL of ArgoCD dynamic
    repoURL: "https://github.com/magzim21/magz8s.git"
    path: argo-projects
    targetRevision: gitops-magz8s-stage
    directory:
      recurse: true
      exclude: "argo-projects/**/values"
    #   jsonnet: {}
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true # not default
      # not default. enable automatic sync when the live cluster's state deviates from the state defined in Git. Default interval 5 secs.
      # selfHeal: true
    syncOptions:
      # - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
