---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fargate-sample-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/magzim21/magz8s.git
    targetRevision: HEAD
    path: eks-apps/fargate-sample-app/
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
