---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/magzim21/magz8s.git
    targetRevision: HEAD
    path: eks-apps/game-2048/
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
