---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promlens
spec:
  selector:
    matchLabels:
      app: promlens
  template:
    metadata:
      labels:
        app: promlens
    spec:
      containers:
      - name: promlens
        image: promlabs/promlens
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: promlens
spec:
  selector:
    app: promlens
  ports:
  - port: 8080
    targetPort: 8080

# http://prometheus-stack-kube-prom-prometheus.prometheus-stack:9090
# https://demo.promlabs.com

