---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: monitoring
  source:
    chart: mimir-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.1.0
    helm:
      releaseName: mimir-cluster
      # parameters:
      # # todo de-hardcode
      #   - name: 'clusterName'
      #     value: ''
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir-cluster
  syncPolicy:
    automated:
      # not default.
      # prune: false
      # not default
      allowEmpty: true
      # not default. enable automatic sync when the live cluster's state deviates from the state defined in Git. Default interval 5 secs.
      selfHeal: true
    syncOptions:
      # - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
