# helm install autoscaler autoscaler/cluster-autoscaler --set autoDiscovery.clusterName=eksdemo1 --set awsRegion=ca-central-1 --set cloudProvider=aws --version 9.10.7
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-efs-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: aws-efs-csi-driver
    repoURL: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
    targetRevision: 2.2.7
    helm:
      releaseName: aws-efs-csi-driver
      parameters:
        - name: "image.repository"
          value: "602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/aws-efs-csi-driver"
        - name: "controller.serviceAccount.create"
          value: "true"
        - name: "controller.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
          value: "arn:aws:iam::249446252531:role/magz8s-prod_efs" # module.iam_assumable_role_efs.this_iam_role_arn
        - name: "storageClasses"
          value: '{"name":"efs-sc","parameters":{"provisioningMode":"efs-ap","fileSystemId":"fs-088df4b50763819b4","directoryPerms":"700","gidRangeStart":"1000","gidRangeEnd":"2000"},"volumeBindingMode":"Immediate"}'
        




  destination:
    server: https://kubernetes.default.svc
    namespace: aws-efs-csi-driver
  syncPolicy:
    automated:
      # not default.
      # prune: false
      # not default
      allowEmpty: true
      # not default. enable automatic sync when the live cluster's state deviates from the state defined in Git. Default interval 5 secs.
      # selfHeal: true
    syncOptions:
      # - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
# Try like here https://github.com/stacksimplify/aws-eks-kubernetes-masterclass/tree/master/17-EKS-Autoscaling-aws-efs-csi-driver
# Try like in shalb
#
