# helm install autoscaler autoscaler/cluster-autoscaler --set autoDiscovery.clusterName=eksdemo1 --set awsRegion=ca-central-1 --set cloudProvider=aws --version 9.10.7
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: cluster-autoscaler
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.10.7
    helm:
      releaseName: cluster-autoscaler
      parameters:
        - name: "autoDiscovery.clusterName"
          value: "magz8s-stage"
        - name: "awsRegion"
          value: "ca-central-1"
        - name: "cloudProvider"
          value: "aws"
          # this role is created here autoscaler-role.tf ; TODO dehardcode
        - name: 'rbac.serviceAccount.annotations.eks\.amazonaws\.com/role-arn'
          value: "arn:aws:iam::249446252531:role/magz8s_stage_cluster_autoscaler"
        # - name: "extraArgs.v"
        #   value: "2"
        - name: "extraArgs.stderrthreshold"
          value: "error"
        - name: "extraArgs.logtostderr"
          value: "true"
        - name: "extraArgs.write-status-configmap"
          value: "true"
        - name: "extraArgs.max-node-provision-time"
          value: "20m0s"
        - name: "extraArgs.scan-interval"
          value: "30s"
        - name: "extraArgs.scale-down-enabled"
          value: "true"
        - name: "extraArgs.scale-down-delay-after-add"
          value: "20m"
        - name: "extraArgs.scale-down-utilization-threshold"
          value: "0.4"
        - name: "extraArgs.max-graceful-termination-sec"
          value: "600"
        - name: "extraArgs.skip-nodes-with-system-pods"
          value: "true"
        - name: "extraArgs.skip-nodes-with-local-storage"
          value: "false"
        - name: "serviceMonitor.enabled"
          value: "false"
        - name: "serviceMonitor.namespace"
          value: "kube-system"
        - name: "serviceMonitor.selector.release"
          value: "cluster-autoscaler"

  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-autoscaler
  syncPolicy:
    automated:
      # not default.
      # prune: false
      # not default
      allowEmpty: true
      # not default. enable automatic sync when the live cluster's state deviates from the state defined in Git. Default interval 5 secs.
      # selfHeal: true
    syncOptions:
      # - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
# Try like here https://github.com/stacksimplify/aws-eks-kubernetes-masterclass/tree/master/17-EKS-Autoscaling-Cluster-Autoscaler
# Try like in shalb
#
