---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-lb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.4.2
    helm:
      releaseName: ingress-lb
      parameters:
        # todo de-hardcode
        - name: "clusterName"
          value: "magz8s-stage"
        - name: "serviceAccount.create"
          value: "true"
        - name: "serviceAccount.name"
          value: "aws-load-balancer-controller"
        - name: 'serviceAccount.annotations.eks\.amazonaws\.com/role-arn'
          value: "arn:aws:iam::249446252531:role/magz8s_stage_aws_load_balancer_controller"
        # - name: 'region'
        #   value: 'ca-central-1'
        # - name: 'vpcId:'
        #   value: 'vpc-0cd84f7b39937284c'
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-lb
  syncPolicy:
    automated:
      # not default.
      # prune: false
      # not default
      allowEmpty: true
      # not default. enable automatic sync when the live cluster's state deviates from the state defined in Git. Default interval 5 secs.
      selfHeal: false

    syncOptions:
      # - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  # https://github.com/argoproj/argo-cd/issues/4276#issuecomment-742165994
  ignoreDifferences:
    # - group: secrets
    #   kind: Secret
    # - group: '*'
    #   kind: '*'
      # name: aws-load-balancer-tls
      # namespace: ingress-lb
      # jqPathExpressions:
      #   - .data
      # Group is on the very right of `kubectl api-resources | grep -i webhook`
    # - kind: MutatingWebhookConfiguration
    #   group: admissionregistration.k8s.io
    #   jsonPointers:
    #     - /webhooks/0/clientConfig/caBundle
    #     - /webhooks/1/clientConfig/caBundle
    #     - /webhooks/2/clientConfig/caBundle
    #     - /webhooks/3/clientConfig/caBundle
    #     - /webhooks/4/clientConfig/caBundle
    #     - /webhooks/5/clientConfig/caBundle
    #     - /webhooks/6/clientConfig/caBundle
    #     - /webhooks/7/clientConfig/caBundle
      # jqPathExpressions:
      #   - .webhooks
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
      - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
      - .webhooks[]?.clientConfig.caBundle
    - kind: Secret
      name: aws-load-balancer-tls
      jqPathExpressions:
      - .data